---
title: "CGLOPS Africa+ROW testing"
author: "Dainius"
date: '2020-03-23'
output: html_document
---
```{r setup, include=FALSE}
library(DT)
source("../src/bfast-cal/01-preprocess.r")
source("../src/bfast-cal/02-detectbreaks.r")
source("../src/bfast-cal/03-batchprocessing.r")
source("../src/bfast-cal/perclass.r")
source("../src/bfast-cal/utils.r")
registerDoParallel(cores=4)
```
```{r load, cache=TRUE}
GlobalData = LoadReferenceData("../data/Data_Global.csv")
```

```{r getrow}
ROWTS = LoadVITS(GlobalData, "", "/data/cgl_lc_bfast/Modis_VIs_ROWPR_UTM_FINAL/", "ROWPR")
ROWData = MergeAllYears(ROWTS, GlobalData)
ROWData = ROWData[order(ROWData$sample_id, ROWData$reference_year),]
CheckReferenceData(ROWData)
```

```{r getafrica, cache=TRUE}
AfricaData = LoadReferenceData("../data/NIRv_16d_byte_full_Africa.csv")
```

```{r combine-africa-row, cache=TRUE}
AfricaData$X = NULL
AfricaData$geom = NULL
AfricaData$continent="Africa"
AfricaData$field_262 = NULL
ROWData$field_30 = NULL
names(ROWData)[1:233] = names(AfricaData)[1:233]
CombinedData = rbind(ROWData, AfricaData[!AfricaData$sample_id %in% ROWData$sample_id,])
CheckReferenceData(CombinedData)
```

```{r addchangetypes}
CombinedData = AddChangeClassCol(CombinedData)
CombinedData = AddChangeProcessCol(CombinedData)
```

```{r}
rm(AfricaData)
rm(ROWData)
gc()
table(CombinedData$changeprocess)
```

# Perform mass statistics

```{r baseline-stat-comparison, cache=TRUE}
ResultBaseline = TestParams(list(
    list(order=3, scrange=NULL),
    list(order=1, formula=response~trend, scrange=NULL),
    list(breaks="BIC", order=2),
    list(breaks="BIC", order=1, seasonfreq = 0.3, formula=response~trend+season, scrange=NULL)
    ), data=CombinedData)
```

```{r}
# Discard changes outside the range
ResultBaseline = ResultBaseline[ResultBaseline$reference_year %in% 2016:2017,]
```

```{r}
datatable(FPStatsPerParam(ResultBaseline))
```

```{r perclass-stats}
htmltools::tagList(lapply(unique(ResultBaseline$call), function(x) datatable(FPStatsPerClass(ResultBaseline[ResultBaseline$call==x,]), caption=x)))
```

```{r perprocess-stats}
htmltools::tagList(lapply(unique(ResultBaseline$call), function(x) datatable(FPStatsPerClass(ResultBaseline[ResultBaseline$call==x,], column = "changeprocess"), caption=x)))
```
