---
title: "BFAST algorithm benchmark"
author: "Dainius Masiliunas, Marius Appel"
date: "17/03/2021"
output: html_document
---

```{r setup, include=FALSE}
source("../src/bfast-cal/01-preprocess.r")
source("../src/bfast-cal/02-detectbreaks.r")
source("../src/bfast-cal/03-batchprocessing.r")
source("../src/bfast-cal/perclass.r")
source("../src/bfast-cal/utils.r")
source("../src/utils/visualise_breakpoints.r")
library(microbenchmark)
```

# Speed benchmark of BFAST vs Lite vs Monitor

## Load data

```{r loaddata}
Dataset = st_read("../data/bfast0n-benchmark-points-pca.gpkg")
DataMat = GetMatrix(Dataset)
```

## Run BFAST on a point to see how long it would take

Setup data:
```{r}
DataPoint = GetTS(c(GetMatrix(Dataset[1,])))
# for bfast(decomp="stl")
DataPointNoNA = na.approx(DataPoint)
# for bfastmonitor
DataPointYearly = lapply(2017:2019+0.25, window, x=DataPoint, start=NULL)
names(DataPointYearly) = 2016:2018
bfm = function(year) bfastmonitor(DataPointYearly[[as.character(year)]], year, response~trend+harmon, 3)
# for all except bfastmonitor
h = ceiling(frequency(DataPoint))
```

Run on one point:

```{r benchmark1}
set_default_options()
system.time(bfast(DataPoint, season = "harmonic", h = h)) # ~5.5s
system.time(bfast(DataPointNoNA, season = "harmonic", h = h, decomp = "stl")) # ~5.5s
system.time(bfast(DataPoint, season = "harmonic", h = h, max.iter=1)) # ~2.5s
system.time(bfast0n(DataPoint, response~trend+harmon, h = h, order = 3)) # ~1.5s
system.time(lapply(2016:2018, bfm)) # 0.05s
set_fast_options()
system.time(bfast(DataPoint, season = "harmonic", h = h)) # ~1.5s
system.time(bfast(DataPointNoNA, season = "harmonic", h = h, decomp = "stl")) # ~1.5s
system.time(bfast(DataPoint, season = "harmonic", h = h, max.iter=1)) # ~0.7s
system.time(bfast0n(DataPoint, response~trend+harmon, h = h, order = 3)) # ~0.3s
system.time(lapply(2016:2018, bfm)) # 0.02s
```

## Define functions for each tested function, running on all points
```{r functiondef}
DataList = split(DataMat, 1:nrow(DataMat))
TSList = lapply(DataList, GetTS)
TSListNoNA = lapply(TSList, na.approx)

TruncTSFx = function(DataPoint) {
    result = lapply(2017:2019+0.25, window, x=DataPoint, start=NULL)
    names(result) = 2016:2018
    return(result)
}
TruncTS = lapply(TSList, TruncTSFx)

bfm1 = function(year, DataPointYearly) bfastmonitor(DataPointYearly[[as.character(year)]], year, response~trend+harmon, 3)
bfm = function(TruncTS) {
    lapply(TruncTS, function(DataPoint) lapply(2016:2018, bfm1, DataPoint))
}

bf0n1 = function(DataPoint) {
    bfast0n(DataPoint, response~trend+harmon, h = h, order = 3)
}
bf0n = function(TSList) {
    lapply(TSList, bf0n1)
}

bf1stlplus = function(DataPoint, ...) bfast(DataPoint, season = "harmonic", h = h, ...)
bfstlplus = function(TSList, ...) lapply(TSList, bf1stlplus, ...)

bf1 = function(DataPoint, ...) bfast(DataPoint, season = "harmonic", h = h, decomp="stl", ...)
bf = function(TSListNoNA, ...) lapply(TSListNoNA, bf1, ...)
```

## Dry run

Remove points that produce errors, e.g. due to too many NAs for stlplus

```{r dryrun, eval=FALSE}
bfstlplusdr = sapply(TSList, function(DataPoint){
    result = try(bf1stlplus(DataPoint, max.iter=1))
    if (class(result) == "try-error")
        return(as.character(result))
    return("Success")
})
Exclude = which(bfstlplusdr != "Success")
```
```{r dryrun-static}
Exclude = c(25, 45, 47, 60, 66, 68, 87, 88, 89, 90, 92, 93, 94, 96, 97, 98, 107, 108, 121, 133, 172, 217, 232, 245, 251, 257, 281, 283, 284, 285, 286, 287, 288, 289, 290, 299, 317, 318, 319, 320, 321, 324, 325, 326, 327, 328, 330, 331)
```
```{r filter-points}
TSList = TSList[-Exclude]
TSListNoNA = TSListNoNA[-Exclude]
TruncTS = TruncTS[-Exclude]
length(TruncTS) # 288 left
```

## Run benchmark

```{r benchmark, cache=TRUE}
set_default_options()
BenchmarkResultSlow = microbenchmark(bfm(TruncTS), bf0n(TSList), bfstlplus(TSList), bfstlplus(TSList, max.iter=1), bf(TSListNoNA), bf(TSListNoNA, max.iter=1), times=5)
set_fast_options()
BenchmarkResultFast = microbenchmark(bfm(TruncTS), bf0n(TSList), bfstlplus(TSList), bfstlplus(TSList, max.iter=1), bf(TSListNoNA), bf(TSListNoNA, max.iter=1), times=5)
```

```{r plot-results}
BenchmarkResultSlow
BenchmarkResultFast
boxplot(BenchmarkResultSlow)
boxplot(BenchmarkResultFast)
autoplot(BenchmarkResultSlow)
autoplot(BenchmarkResultFast)
str(BenchmarkResultSlow)
str(BenchmarkResultFast)
```
