---
title: "CGLOPS global point testing"
author: "Dainius"
date: '2020-03-23'
output: html_document
---

```{r setup, include=FALSE}
library(DT)
source("../src/bfast-cal/01-preprocess.r")
source("../src/bfast-cal/02-detectbreaks.r")
source("../src/bfast-cal/03-batchprocessing.r")
source("../src/bfast-cal/perclass.r")
source("../src/bfast-cal/utils.r")
registerDoParallel(cores=4)
```
```{r load, cache=TRUE}
GlobalData = LoadReferenceData("../data/Data_Global.csv")
```
```{r addchangetypes}
GlobalData = AddChangeClassCol(GlobalData)
GlobalData = AddChangeProcessCol(GlobalData)
GlobalData = GlobalData[GlobalData$reference_year %in% 2016:2018,] # Discard any changes in 2015, reference does not track that
```

```{r}
table(CombinedData$changeprocess)
```

# Perform mass statistics

```{r baseline-stat-comparison, cache=TRUE}
ResultBaseline = TestParams(list(
    list(order=3, scrange=NULL),
    list(order=1, formula=response~trend, scrange=NULL),
    list(breaks="BIC", order=2),
    list(breaks="BIC", order=1, seasonfreq = 0.3, formula=response~trend+season, scrange=NULL)
    ), data=GlobalData)
```

```{r}
datatable(FPStatsPerParam(ResultBaseline))
```

```{r perclass-stats}
for (call in unique(ResultBaseline$call))
{
    print(call)
    datatable(FPStatsPerClass(ResultBaseline[ResultBaseline$call==call,]))
}
```

```{r perprocess-stats}
for (call in unique(ResultBaseline$call))
{
    print(call)
    datatable(FPStatsPerClass(ResultBaseline[ResultBaseline$call==call,], column = "changeprocess"))
}
```

